
# Alternative App Engine configuration (if you change your mind)
runtime: nodejs18

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  - url: /static
    static_dir: dist/assets
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
