// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htvnhifyfzhhsvqowzda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dm5oaWZ5ZnpoaHN2cW93emRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDgxMDMsImV4cCI6MjA2NTUyNDEwM30.cPsOWpdVmhvVvyJ7X59I4XA2ieRn9cntYLuRrgCCSls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);